# Site settings
title: docs.phant.xyz
email: phant@tugzrida.xyz
github: Tugzrida/phant
twitter: Tugzrida
description: "data collection for the internet of things. developed by sparkfun electronics and tugzrida."
baseurl: ""
url: "https://docs.phant.xyz"

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  auto_ids: true
